[workspace]
resolver = "3"
members = [
    "crates/radia-bake",
    "crates/radia-demo",
    "crates/radia-math",
    "crates/radia-render",
]

[workspace.package]
edition = "2024"
rust-version = "1.95"
license = "Apache-2.0"
repository = "https://github.com/LairdWT/Radia"

[workspace.dependencies]
png = "=0.18.1"
wgpu = { version = "=26.0.1", default-features = false, features = ["std", "vulkan", "wgsl"] }
winit = { version = "=0.30.13", default-features = false, features = ["rwh_06", "wayland", "wayland-dlopen", "x11"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
module_name_repetitions = "allow"
